```{r}
rm(list=ls())
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(caret))
suppressPackageStartupMessages(library(MASS))

df_alpha <- read_csv("../data/alpha_event_data.csv", show_col_types = FALSE)
df_beta <- read_csv("../data/beta_event_data.csv", show_col_types = FALSE)
df_gamma <- read_csv("../data/gamma_event_data.csv", show_col_types = FALSE)
band_names <- rep(c('alpha', 'beta', 'gamma'),
                  times = c(nrow(df_alpha), nrow(df_beta), nrow(df_gamma)))

df <- rbind(df_alpha, df_beta, df_gamma)
names(df) <- tolower(str_replace_all(names(df_alpha), ' ', '_')) # clean names
df['freq_band'] <- band_names
df['position'] <- as.character(df$position)
df['layout'] <- as.character(df$layout)
```

```{r}
median_reaction_time <- median(df$reaction_time, na.rm = TRUE)
median_reach_time <- median(df$reach_time, na.rm = TRUE)

# Calculate the statistics and add a binary variable column based on the median reaction_time
stats_df <- df %>%
  group_by(trial, freq_band) %>%
  summarize(
    mean_freq_span = mean(frequency_span, na.rm = TRUE),
    std_freq_span = sd(frequency_span, na.rm = TRUE),
    mean_event_duration = mean(event_duration, na.rm = TRUE),
    std_event_duration = sd(event_duration, na.rm = TRUE),
    mean_peak_time = mean(peak_time, na.rm = TRUE),
    std_peak_time = sd(peak_time, na.rm = TRUE),
    mean_peak_power = mean(peak_power, na.rm = TRUE),
    std_peak_power = sd(peak_power, na.rm = TRUE),
    count = n(),
    .groups = 'drop'
  ) 

# Add reaction_time, reach_time, and reaction_time_binary columns
summary_df <- df %>%
  group_by(trial) %>%
  summarize(
    reaction_time = first(reaction_time),
    reach_time = first(reach_time),
    reaction_time_binary = ifelse(first(reaction_time) > median_reaction_time, 1, 0),
    reach_time_binary = ifelse(first(reach_time) > median_reach_time, 1, 0),
    .groups = 'drop'
  )

# Pivot the statistics dataframe from long to wide format
output_df <- stats_df %>%
  pivot_wider(
    id_cols = trial,
    names_from = freq_band,
    values_from = c(mean_freq_span, std_freq_span, mean_event_duration, std_event_duration, mean_peak_time, std_peak_time, mean_peak_power, std_peak_power, count),
    names_sep = "_"
  ) %>%
  left_join(summary_df, by = "trial")

output_df
```

```{r}
output_df <- na.omit(output_df)

# computes the LOO cross validation for all data without missing values
ctrl_LOOCV <- trainControl(method = "LOOCV")
model_LOO <- train(reaction_time ~ mean_freq_span_gamma + mean_event_duration_gamma 
                   + std_event_duration_gamma + std_peak_time_beta + std_peak_power_beta 
                   + count_beta + count_gamma, data = output_df, 
                   method = "lm", trControl = ctrl_LOOCV)
print(model_LOO)
```

```{r}
# computes the K-fold cross validation with 10 folds for all data without missing values
ctrl_Kfold <- trainControl(method = "cv", number = 10)
model_Kfold <- train(reaction_time ~ mean_freq_span_gamma + mean_event_duration_gamma 
                     + std_event_duration_gamma + std_peak_time_beta + std_peak_power_beta 
                     + count_beta + count_gamma, data = output_df,
                     method = "lm", trControl = ctrl_Kfold)
print(model_Kfold)
```

```{r}
# creates a scatter plot of predicted vs. true values of LOO cross validation
loocv_plot <- ggplot(output_df, aes(x = reaction_time, y = model_LOO$pred[, "pred"])) +
  ggtitle("LOO Cross Validation: Predicted vs. True") +
  xlab("True Value") +
  ylab("Predicted Value") +
  geom_point(size = 0.5) +
  theme_bw()
loocv_plot
```

```{r}
# creates a scatter plot of predicted vs. true values of LOO cross validation
kfoldcv_plot <- ggplot(output_df, aes(x = reaction_time, y = predict(model_Kfold))) +
  ggtitle("K-Fold Cross Validation: Predicted vs. True") +
  xlab("True Value") +
  ylab("Predicted Value") +
  geom_point(size = 0.5) +
  theme_bw()
kfoldcv_plot
```