---
title: "workspace.project"
author: "Nicholas Tolley"
date: "2023-04-12"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

EDA below:

```{r}
rm(list=ls())
library(dplyr)
library(ggplot2)
library(tidyverse)
library(plotly)
df_alpha <- read_csv("../data/alpha_event_data.csv")
df_beta <- read_csv("../data/beta_event_data.csv")
df_gamma <- read_csv("../data/gamma_event_data.csv")
band_names <- rep(c('alpha', 'beta', 'gamma'),
                  times=c(nrow(df_alpha), nrow(df_beta), nrow(df_gamma)))

df <- rbind(df_alpha, df_beta, df_gamma)
names(df) <- tolower(str_replace_all(names(df_alpha), ' ', '_')) # clean names
df['freq_band'] <- band_names
df['position'] <- as.character(df$position)
df['layout'] <- as.character(df$layout)

#behavior_cols <- c('reaction_time', 'reach_time', 'grip_time')
behavior_df <- group_by(df, trial) %>% summarise(reaction_time=first(reaction_time),
                                  reach_time=first(reach_time),
                                  grip_time=first(grip_time), position=first(position),
                                  layout=first(layout))

```

```{r}
#select(df_gamma, peak_time, normalized_peak_power, peak_frequency) %>%
  #mutate(`Peak Frequency` = peak_frequency) %>% 
  ggplot(data=df, aes(x = peak_time, y = normalized_peak_power, color=peak_frequency)) +
  geom_point(alpha = 0.3) +
  scale_x_continuous(breaks = seq(from = 0, to = 2, by = 0.25)) +
  scale_y_log10() +
  labs(x = 'Peak Time', y = 'Normalized Peak Power') + facet_wrap('freq_band', ncol=1) + scale_y_log10() +
  theme_bw()
```

```{r}

fig <- ggplot(data=behavior_df, aes(x=reaction_time, y=reach_time, color=position)) +
  geom_point() + scale_x_log10() + scale_y_log10() + facet_wrap('layout', nrow=2, ncol=2) +
  theme_bw() + labs(x='Reaction Time (s)', y='Reach Time (s)')

ggsave(filename='behavior_scatter.svg', plot=fig)


```

```{r}
# dim(df) #[1] 699  23
# df.NAs <- colSums(is.na(df))
# # NAs in Pupil Varibale: 408
# # No NAs reported in other variables
# 
# df.omitNAs <- na.omit(df)
# dim(df.omitNAs) # [1] 291  23
# Removed rows with missing values in Pupil

# df.omitPupil <- subset(df,select=-c(Pupil, Lower.Frequency, Trial))
# dim(df.omitPupil) # [1] 699  22

# df <- na.omit(df)
df <- df %>% select(-Pupil, -Lower.Frequency.Bound, -Trial)

```

Linear Models Below:

Target Variable: (Relate behavior variables to task condition) •
Reaction Time • Reach Time • Grip Time • Total Movement Time

Relate to: • Position • Layout • Position + Layout

```{r}

# Target Variable: Reaction Time
df.lm.ReactionTime <- lm(Reaction.Time ~ ., data = df)
summary(df.lm.ReactionTime)

df.lm.backward.ReactionTime <- step(df.lm.ReactionTime,direction = "backward")
summary(df.lm.backward.ReactionTime)

df.lm.forward.ReactionTime <- step(df.lm.ReactionTime,direction = "forward")
summary(df.lm.forward.ReactionTime)

# # Target Variable: Reach Time
# df.lm.ReachTime <- lm(Reach.Time ~ .,data = df.omitPupil)
# summary(df.lm.ReachTime)
# 
# df.lm.backward.ReachTime <- step(df.lm.ReachTime, direction = "backward")
# summary(df.lm.backward.ReachTime)
# 
# df.lm.forward.ReachTime <- step(df.lm.ReachTime,direction = "forward")
# summary(df.lm.forward.ReachTime)
# 
# # Target Variable: Grip Time 
# df.lm.GripTime <- lm(Grip.Time ~ .,data = df.omitPupil)
# summary(df.lm.GripTime)
# 
# df.lm.backward.GripTime <- step(df.lm.GripTime, direction = "backward")
# summary(df.lm.backward.GripTime)
# 
# df.lm.forward.GripTime <- step(df.lm.GripTime,direction = "forward")
# summary(df.lm.forward.GripTime)
# 
# # Target Variable: Total Movement Time
# df.lm.EventDuration <- lm(Event.Duration ~ ., data = df.omitPupil)
# summary(df.lm.EventDuration)
# 
# df.lm.backward.EventDuration <- step(df.lm.EventDuration, direction = "backward")
# summary(df.lm.backward.EventDuration)
# 
# df.lm.forward.EventDuration <- step(df.lm.EventDuration,direction = "forward")
# summary(df.lm.forward.EventDuration)

```
